### ISSUE TITLE
Doesn't work on actual iPhone (7, iOS 10)?

### ISSUE THREAD

**Issue by booboothefool** [ollija/react-native-sortable-grid#3]
The library works great on iPhone simulator (it's amazing!), however when testing on an actual iPhone, I can't drag anything.

Do I need to do anything special to get it to work on an actual device?

```
iPhone 7, iOS 10
"react-native": "^0.36.0",
"react-native-sortable-grid": "^1.2.1",
```

**Comment by ollija** [comment]
Sorry to hear that. It should work on an actual device just as well.
Have you tried running it with "JS Dev Mode"-option turned off and without remote JS debugging?

**Comment by booboothefool** [comment]
@ollija Yes, I've tried running it in xcode Release build (Profiling mode), if that's what you mean.

**Comment by ollija** [comment]
I tried running the examples of the library on an actual device (Iphone 6 IOS 10) with release build and they worked as expected. Unfortunately I don't have an Iphone 7 to test this with.

Is it possible for you to provide example code that produces this?

**Comment by andrewnoh** [comment]
@ollija I'm going to try running your example code on my iPhone 7. I will update this post with the result!

**Comment by booboothefool** [comment]
@ollija The example code https://github.com/ollija/react-native-sortable-grid/blob/master/example/deletionExample.js is not working on my iPhone 7 (but works in simulator).

Here is a gif of me trying to initiate the drag, nothing happens 😔 :
![2016-11-15_16_02_56](https://cloud.githubusercontent.com/assets/13257645/20324109/464550de-ab4d-11e6-8846-e91c79b84b9a.gif)

**Comment by ollija** [comment]
Could you try with the latest version I just pushed and tell me if it worked?

**Comment by booboothefool** [comment]
@ollija (before you pushed) I just tried it with my iPhone 5. It works perfectly with iPhone 5!

I will try out your new version on iPhone 7 now.

**Comment by booboothefool** [comment]
@ollija After your latest push, it is now working beautifully on my iPhone 7! Thank you so much for your badass, one-of-a-kind library!

Out of curiosity, what was the issue? Is there something iPhone 7 does differently with touch handlers than previous versions?

**Comment by ollija** [comment]
Thanks! I'm really glad this worked out.

It seems that on iPhone 7 a view listening to touch events with `panResponder` prevents the children from capturing touch events if
`onMoveShouldSetPanResponder` and
`onMoveShouldSetPanResponderCapture`
are true -  but not on other iPhones.

I have absolutely no idea why this happens, but it could be fixed in this case because we don't need to capture both press and drag events at the same time.

So the fix was like, "don't capture drag events before the user has initiated the drag with a long-press, and don't capture press events while dragging"
